import { MENU, type MenuSlug } from "../src/config/menu";

/**
 * Pohon menu lengkap (12 domain, 63 layar) supaya sidebar desktop bisa dinilai
 * utuh. Slug diambil dari `src/config/menu.ts`, bukan disalin sebagai string;
 * pengelompokan domain → layar hanya ada di sini karena menu.ts sengaja tidak
 * menyimpan pohonnya (pohon milik be-sada). Dipakai juga `menu.test.ts` untuk
 * memeriksa ikon layar per domain.
 */
export const TREE: Record<string, MenuSlug[]> = {
  [MENU.KEJEMAATAN]: [
    MENU.DAFTAR_JEMAAT,
    MENU.KELUARGA,
    MENU.PERNIKAHAN,
    MENU.RIWAYAT_JEMAAT,
    MENU.ROLE_JEMAAT,
    MENU.BAPEL,
    MENU.WILAYAH,
    MENU.REPORT_JEMAAT,
  ],
  [MENU.PELAYANAN]: [
    MENU.JADWAL_PELAYAN,
    MENU.TEMPLATE_JADWAL,
    MENU.DAFTAR_PELAYAN,
    MENU.ROLE_PELAYAN,
    MENU.SKILL_MUSIK,
  ],
  [MENU.PERIBADAHAN]: [MENU.IBADAH, MENU.TIPE_IBADAH],
  [MENU.KEGIATAN]: [
    MENU.EVENT,
    MENU.PENDAFTARAN_EVENT,
    MENU.GALERI,
    MENU.PENGUMUMAN,
  ],
  [MENU.FASILITAS]: [MENU.PEMINJAMAN_RUANG, MENU.RUANG],
  [MENU.INVENTARIS]: [
    MENU.BARANG,
    MENU.TIPE_BARANG,
    MENU.SATUAN,
    MENU.BARANG_PERSEDIAAN,
    MENU.MUTASI_STOK,
    MENU.STOK_OPNAME,
    MENU.SIKLUS_ASET,
    MENU.PENYUSUTAN,
  ],
  [MENU.PENGADAAN]: [
    MENU.SUPPLIER,
    MENU.PERMINTAAN_PEMBELIAN,
    MENU.PESANAN_PEMBELIAN,
    MENU.PENERIMAAN_BARANG,
    MENU.RETUR_PEMBELIAN,
    MENU.FAKTUR_SUPPLIER,
  ],
  [MENU.KEUANGAN]: [
    MENU.PERSEMBAHAN,
    MENU.TIPE_PERSEMBAHAN,
    MENU.AKUN,
    MENU.KAS_MASUK,
    MENU.KAS_KELUAR,
    MENU.JURNAL,
    MENU.PERIODE_FISKAL,
    MENU.LAPORAN_KEUANGAN,
    MENU.PEMBAYARAN,
    MENU.MATA_UANG,
    MENU.SETELAN_AKUNTANSI,
  ],
  [MENU.ANGGARAN]: [MENU.PROGRAM, MENU.LAPORAN_BUDGET, MENU.PAGU_ANGGARAN],
  [MENU.SDM]: [
    MENU.KARYAWAN,
    MENU.CUTI,
    MENU.TIPE_CUTI,
    MENU.KONTRAK_KARYAWAN,
    MENU.ABSENSI_KARYAWAN,
    MENU.PAYROLL,
    MENU.KOMPONEN_PAYROLL,
    MENU.PAJAK_PPH21,
  ],
  [MENU.PERSETUJUAN]: [MENU.PERMINTAAN_PERSETUJUAN, MENU.SETELAN_PERSETUJUAN],
  [MENU.PENGATURAN]: [
    MENU.USER,
    MENU.ROLE_USER,
    MENU.ACTIVITY_LOG,
    MENU.HARI_LIBUR,
  ],
};

/**
 * Nama tampilan tiap domain & layar, disalin apa adanya dari `MENU_TREE` di
 * `be-sada/src/common/constants/menu.ts` — supaya mock menampilkan "SDM" dan
 * "Badan Pelayanan", bukan tebakan Title Case dari slug. Tipe `Record` penuh:
 * slug baru di menu.ts gagal typecheck sampai namanya ditambahkan di sini.
 */
export const NAME: Record<MenuSlug, string> = {
  [MENU.KEJEMAATAN]: "Kejemaatan",
  [MENU.DAFTAR_JEMAAT]: "Daftar Jemaat",
  [MENU.KELUARGA]: "Keluarga",
  [MENU.PERNIKAHAN]: "Pernikahan",
  [MENU.RIWAYAT_JEMAAT]: "Riwayat Jemaat",
  [MENU.ROLE_JEMAAT]: "Role Jemaat",
  [MENU.BAPEL]: "Badan Pelayanan",
  [MENU.WILAYAH]: "Wilayah",
  [MENU.REPORT_JEMAAT]: "Laporan Jemaat",
  [MENU.PELAYANAN]: "Pelayanan",
  [MENU.JADWAL_PELAYAN]: "Jadwal Pelayan",
  [MENU.TEMPLATE_JADWAL]: "Template Jadwal",
  [MENU.DAFTAR_PELAYAN]: "Daftar Pelayan",
  [MENU.ROLE_PELAYAN]: "Role Pelayan",
  [MENU.SKILL_MUSIK]: "Skill Musik",
  [MENU.PERIBADAHAN]: "Peribadahan",
  [MENU.IBADAH]: "Ibadah",
  [MENU.TIPE_IBADAH]: "Tipe Ibadah",
  [MENU.KEGIATAN]: "Kegiatan",
  [MENU.EVENT]: "Event",
  [MENU.PENDAFTARAN_EVENT]: "Pendaftaran Event",
  [MENU.GALERI]: "Galeri",
  [MENU.PENGUMUMAN]: "Pengumuman",
  [MENU.FASILITAS]: "Fasilitas",
  [MENU.PEMINJAMAN_RUANG]: "Peminjaman Ruang",
  [MENU.RUANG]: "Ruang",
  [MENU.INVENTARIS]: "Inventaris",
  [MENU.BARANG]: "Barang",
  [MENU.TIPE_BARANG]: "Tipe Barang",
  [MENU.SATUAN]: "Satuan",
  [MENU.BARANG_PERSEDIAAN]: "Barang Persediaan",
  [MENU.MUTASI_STOK]: "Mutasi Stok",
  [MENU.STOK_OPNAME]: "Stok Opname",
  [MENU.SIKLUS_ASET]: "Siklus Aset",
  [MENU.PENYUSUTAN]: "Penyusutan",
  [MENU.PENGADAAN]: "Pengadaan",
  [MENU.SUPPLIER]: "Supplier",
  [MENU.PERMINTAAN_PEMBELIAN]: "Permintaan Pembelian",
  [MENU.PESANAN_PEMBELIAN]: "Pesanan Pembelian",
  [MENU.PENERIMAAN_BARANG]: "Penerimaan Barang",
  [MENU.RETUR_PEMBELIAN]: "Retur Pembelian",
  [MENU.FAKTUR_SUPPLIER]: "Faktur Supplier",
  [MENU.KEUANGAN]: "Keuangan",
  [MENU.PERSEMBAHAN]: "Persembahan",
  [MENU.TIPE_PERSEMBAHAN]: "Tipe Persembahan",
  [MENU.AKUN]: "Akun",
  [MENU.KAS_MASUK]: "Kas Masuk",
  [MENU.KAS_KELUAR]: "Kas Keluar",
  [MENU.JURNAL]: "Jurnal",
  [MENU.PERIODE_FISKAL]: "Periode Fiskal",
  [MENU.LAPORAN_KEUANGAN]: "Laporan Keuangan",
  [MENU.PEMBAYARAN]: "Pembayaran",
  [MENU.MATA_UANG]: "Mata Uang",
  [MENU.SETELAN_AKUNTANSI]: "Setelan Akuntansi",
  [MENU.ANGGARAN]: "Anggaran",
  [MENU.PROGRAM]: "Program",
  [MENU.LAPORAN_BUDGET]: "Laporan Pemakaian Budget",
  [MENU.PAGU_ANGGARAN]: "Pagu Anggaran",
  [MENU.SDM]: "SDM",
  [MENU.KARYAWAN]: "Karyawan",
  [MENU.CUTI]: "Cuti",
  [MENU.TIPE_CUTI]: "Tipe Cuti",
  [MENU.KONTRAK_KARYAWAN]: "Kontrak Karyawan",
  [MENU.ABSENSI_KARYAWAN]: "Absensi Karyawan",
  [MENU.PAYROLL]: "Penggajian",
  [MENU.KOMPONEN_PAYROLL]: "Komponen Payroll",
  [MENU.PAJAK_PPH21]: "Pajak PPh21",
  [MENU.PERSETUJUAN]: "Persetujuan",
  [MENU.PERMINTAAN_PERSETUJUAN]: "Permintaan Persetujuan",
  [MENU.SETELAN_PERSETUJUAN]: "Setelan Alur Persetujuan",
  [MENU.PENGATURAN]: "Pengaturan",
  [MENU.USER]: "User",
  [MENU.ROLE_USER]: "Role User",
  [MENU.ACTIVITY_LOG]: "Log Aktivitas",
  [MENU.HARI_LIBUR]: "Hari Libur",
};
