import { MENU, type MenuSlug } from "../src/config/menu";

/**
 * Pohon menu lengkap (14 domain, 64 layar) supaya sidebar desktop bisa dinilai
 * utuh. Slug diambil dari `src/config/menu.ts`, bukan disalin sebagai string;
 * pengelompokan domain → layar hanya ada di sini karena menu.ts sengaja tidak
 * menyimpan pohonnya (pohon milik be-sada). Dipakai juga `menu.test.ts` untuk
 * memeriksa ikon layar per domain.
 */
export const TREE: Record<string, MenuSlug[]> = {
  [MENU.KEJEMAATAN]: [
    MENU.DAFTAR_JEMAAT,
    MENU.KELUARGA,
    MENU.PERNIKAHAN,
    MENU.RIWAYAT_JEMAAT,
    MENU.ROLE_JEMAAT,
    MENU.BAPEL,
    MENU.WILAYAH,
  ],
  [MENU.PELAYANAN]: [
    MENU.JADWAL_PELAYAN,
    MENU.TEMPLATE_JADWAL,
    MENU.DAFTAR_PELAYAN,
    MENU.ROLE_PELAYAN,
    MENU.SKILL_MUSIK,
  ],
  [MENU.PERIBADAHAN]: [MENU.IBADAH, MENU.TIPE_IBADAH],
  [MENU.KEGIATAN]: [
    MENU.EVENT,
    MENU.PENDAFTARAN_EVENT,
    MENU.GALERI,
    MENU.PENGUMUMAN,
  ],
  [MENU.FASILITAS]: [MENU.PEMINJAMAN_RUANG, MENU.RUANG],
  [MENU.INVENTORY]: [
    MENU.ITEM_CATEGORY,
    MENU.SATUAN,
    MENU.STOCK_ITEM,
    MENU.STOCK_MOVEMENT,
    MENU.STOK_OPNAME,
  ],
  [MENU.FIXED_ASSET]: [
    MENU.ASSET_MASTER,
    MENU.ASSET_TRANSACTION,
    MENU.DEPRECIATION,
  ],
  [MENU.PROCUREMENT]: [
    MENU.SUPPLIER,
    MENU.PURCHASE_REQUEST,
    MENU.PURCHASE_ORDER,
    MENU.GOODS_RECEIPT,
    MENU.PURCHASE_RETURN,
    MENU.SUPPLIER_INVOICE,
  ],
  [MENU.FINANCE]: [
    MENU.PERSEMBAHAN,
    MENU.TIPE_PERSEMBAHAN,
    MENU.CHART_OF_ACCOUNT,
    MENU.KAS_MASUK,
    MENU.KAS_KELUAR,
    MENU.BANK_DEPOSIT,
    MENU.JOURNAL_ENTRY,
    MENU.FISCAL_PERIOD,
    MENU.PAYMENT,
    MENU.CURRENCY,
    MENU.ACCOUNTING_SETTING,
  ],
  [MENU.BUDGETING]: [MENU.PROGRAM, MENU.BUDGET],
  [MENU.REPORT]: [
    MENU.REPORT_JEMAAT,
    MENU.FINANCIAL_STATEMENT,
    MENU.BUDGET_REALIZATION,
  ],
  [MENU.HR]: [
    MENU.EMPLOYEE,
    MENU.LEAVE,
    MENU.LEAVE_TYPE,
    MENU.EMPLOYEE_CONTRACT,
    MENU.ATTENDANCE,
    MENU.PAYROLL,
    MENU.PAYROLL_COMPONENT,
    MENU.PAJAK_PPH21,
  ],
  [MENU.APPROVAL]: [MENU.APPROVAL_REQUEST, MENU.APPROVAL_WORKFLOW],
  [MENU.SETTINGS]: [MENU.USER, MENU.USER_ROLE, MENU.ACTIVITY_LOG, MENU.HOLIDAY],
};

/**
 * Nama tampilan tiap domain & layar, disalin apa adanya dari `MENU_TREE` di
 * `be-sada/src/common/constants/menu.ts` — supaya mock menampilkan "Badan
 * Pelayanan" dan "Stok Opname", bukan tebakan Title Case dari slug. Tipe `Record` penuh:
 * slug baru di menu.ts gagal typecheck sampai namanya ditambahkan di sini.
 */
export const NAME: Record<MenuSlug, string> = {
  [MENU.KEJEMAATAN]: "Kejemaatan",
  [MENU.DAFTAR_JEMAAT]: "Daftar Jemaat",
  [MENU.KELUARGA]: "Keluarga",
  [MENU.PERNIKAHAN]: "Pernikahan",
  [MENU.RIWAYAT_JEMAAT]: "Riwayat Jemaat",
  [MENU.ROLE_JEMAAT]: "Role Jemaat",
  [MENU.BAPEL]: "Badan Pelayanan",
  [MENU.WILAYAH]: "Wilayah",
  [MENU.PELAYANAN]: "Pelayanan",
  [MENU.JADWAL_PELAYAN]: "Jadwal Pelayan",
  [MENU.TEMPLATE_JADWAL]: "Template Jadwal",
  [MENU.DAFTAR_PELAYAN]: "Daftar Pelayan",
  [MENU.ROLE_PELAYAN]: "Role Pelayan",
  [MENU.SKILL_MUSIK]: "Skill Musik",
  [MENU.PERIBADAHAN]: "Peribadahan",
  [MENU.IBADAH]: "Ibadah",
  [MENU.TIPE_IBADAH]: "Tipe Ibadah",
  [MENU.KEGIATAN]: "Kegiatan",
  [MENU.EVENT]: "Event",
  [MENU.PENDAFTARAN_EVENT]: "Pendaftaran Event",
  [MENU.GALERI]: "Galeri",
  [MENU.PENGUMUMAN]: "Pengumuman",
  [MENU.FASILITAS]: "Fasilitas",
  [MENU.PEMINJAMAN_RUANG]: "Peminjaman Ruang",
  [MENU.RUANG]: "Ruang",
  [MENU.INVENTORY]: "Inventory",
  [MENU.ITEM_CATEGORY]: "Item Category",
  [MENU.SATUAN]: "Satuan",
  [MENU.STOCK_ITEM]: "Stock Item",
  [MENU.STOCK_MOVEMENT]: "Stock Movement",
  [MENU.STOK_OPNAME]: "Stok Opname",
  [MENU.FIXED_ASSET]: "Fixed Asset",
  [MENU.ASSET_MASTER]: "Asset Master",
  [MENU.ASSET_TRANSACTION]: "Asset Transaction",
  [MENU.DEPRECIATION]: "Depreciation",
  [MENU.PROCUREMENT]: "Procurement",
  [MENU.SUPPLIER]: "Supplier",
  [MENU.PURCHASE_REQUEST]: "Purchase Request",
  [MENU.PURCHASE_ORDER]: "Purchase Order",
  [MENU.GOODS_RECEIPT]: "Goods Receipt",
  [MENU.PURCHASE_RETURN]: "Purchase Return",
  [MENU.SUPPLIER_INVOICE]: "Supplier Invoice",
  [MENU.FINANCE]: "Finance",
  [MENU.PERSEMBAHAN]: "Persembahan",
  [MENU.TIPE_PERSEMBAHAN]: "Tipe Persembahan",
  [MENU.CHART_OF_ACCOUNT]: "Chart of Account",
  [MENU.KAS_MASUK]: "Kas Masuk",
  [MENU.KAS_KELUAR]: "Kas Keluar",
  [MENU.BANK_DEPOSIT]: "Bank Deposit",
  [MENU.JOURNAL_ENTRY]: "Journal Entry",
  [MENU.FISCAL_PERIOD]: "Fiscal Period",
  [MENU.PAYMENT]: "Payment",
  [MENU.CURRENCY]: "Currency",
  [MENU.ACCOUNTING_SETTING]: "Accounting Setting",
  [MENU.BUDGETING]: "Budgeting",
  [MENU.PROGRAM]: "Program",
  [MENU.BUDGET]: "Budget",
  [MENU.HR]: "HR",
  [MENU.EMPLOYEE]: "Employee",
  [MENU.LEAVE]: "Leave",
  [MENU.LEAVE_TYPE]: "Leave Type",
  [MENU.EMPLOYEE_CONTRACT]: "Employee Contract",
  [MENU.ATTENDANCE]: "Attendance",
  [MENU.PAYROLL]: "Payroll",
  [MENU.PAYROLL_COMPONENT]: "Payroll Component",
  [MENU.PAJAK_PPH21]: "PPh21",
  [MENU.REPORT]: "Report",
  [MENU.REPORT_JEMAAT]: "Laporan Jemaat",
  [MENU.FINANCIAL_STATEMENT]: "Financial Statement",
  [MENU.BUDGET_REALIZATION]: "Budget Realization",
  [MENU.APPROVAL]: "Approval",
  [MENU.APPROVAL_REQUEST]: "Approval Request",
  [MENU.APPROVAL_WORKFLOW]: "Approval Workflow",
  [MENU.SETTINGS]: "Settings",
  [MENU.USER]: "User",
  [MENU.USER_ROLE]: "User Role",
  [MENU.ACTIVITY_LOG]: "Activity Log",
  [MENU.HOLIDAY]: "Holiday",
};
